- name: "Xiaomi Mi Router 4A"
  id: "xiaomi_mir4a"

- name: "TP-Link Archer C7"
  id: "tplink_c7"

- name: "Linksys WRT1900ACS"
  id: "linksys_wrt1900acs"

- name: "Netgear R7800"
  id: "netgear_r7800"

- name: "GL.iNet GL-AR750S"
  id: "glinet_ar750s"

