ap-cap-ac:
  openwrt-devid: mikrotik:mikrotik_rbcapgi-5acd2nd_cap_ac
  name: AP Mikrotik CAP ac
hap-ac:
  openwrt-devid: mikrotik:mikrotik_rb962uigs-5hact2hnt_hap_ac
  name: Mikrotik HAP ac
r-cap-ac:
  openwrt-devid: mikrotik:mikrotik_rbcapgi-5acd2nd_cap_ac
  name: Roter CAP ac
zip-misky:
  openwrt-devid: xiaomi:xiaomi_mini_v1
  name: MiniMi router
ap-eap225-v4:
  openwrt-devid: tp-link:tp-link_eap225_v4
  name: AP TP-Link eap225-v4
hap-ac2:
  openwrt-devid: mikrotik:mikrotik_rbd52g-5hacd2hnd-tc_hap_ac2
  name: Mikrotik HAP ac2
zip-turris:
  openwrt-devid: turris:turris_turris_omnia
  name: Turris Omnia
ap-mini:
  openwrt-devid: xiaomi:xiaomi_mini_v1
  name: MiniMi AP
ap-u6-lite:
  openwrt-devid: ubiquiti:ubiquiti_unifi_6_lite
  name: AP Ui6Lite
ap-wap-ac-mipsbe:
  openwrt-devid: mikrotik:mikrotik_wap_ac_rbwapg-5hacd2hnd
  name: AP Mikrotik WAP ac mipsbe
mikro-951ui:
  openwrt-devid: mikrotik:mikrotik_rb951ui-2hnd
  name: Mikrotik 951ui
ap-zyx-nwa1123:
  openwrt-devid: zyxel:zyxel_nwa1123-ac
  name: Zyxel NWA1123
Nika-dream:
  openwrt-devid: xiaomi:xiaomi_redmi_router_ac2100
  name: Nika Dream RedMi
zip-3200:
  openwrt-devid: linksys:linksys_wrt3200acm
  name: WRT3200-ACM
